"""reverted last_seen

Revision ID: 921654d231e4
Revises: be955eeb40df
Create Date: 2024-01-30 17:40:36.026745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921654d231e4'
down_revision = 'be955eeb40df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
